# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171127_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alias', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'my_user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
